font_family Fira Mono
font_size 12
background_opacity 1.0
confirm_os_window_close 0
enable_audio_bell no
mouse_hide_wait 2.0
window_padding_width 4
include colors-matugen.conf
shell_integration enabled
allow_remote_control yes
map ctrl+f launch --type=os-window --cwd=current ~/.config/kitty/tab-search.sh
