#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration
font_family                 JetBrainsMono Nerd Font
font_size                   12
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
remember_window_size        no
initial_window_width        950
initial_window_height       500
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
window_padding_width        10
hide_window_decorations     yes
background_opacity          0.8
dynamic_background_opacity  yes
confirm_os_window_close     0
selection_foreground        none
selection_background        none

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

confirm_os_window_close -1

map ctrl+shift+r layout_action rotate

map ctrl+shift+t launch --type=tab --cwd=current

# Open new split/window in current directory
map ctrl+shift+enter launch --type=window --cwd=current

# Open brand new OS window in current directory
map ctrl+shift+n launch --type=os-window --cwd=current

# Animated cursor follows text
include $HOME/.config/ml4w/settings/kitty-cursor-trail.conf

# Include wallpaper colors
include colors-matugen.conf

# Include Custom Configuration
# Create the file custom.conf in ~/.config/kitty to overwrite the default configuration
include $HOME/.config/kitty/custom.conf

