font_family JetBrainsMono Nerd Font 
font_size 12
background_opacity 0.5
dynamic_background_opacity  yes
confirm_os_window_close -1
enable_audio_bell no
mouse_hide_wait 2.0
window_padding_width 4
include colors-matugen.conf
shell_integration enabled
allow_remote_control yes
selection_foreground        none
selection_background        none
# map ctrl+f launch --type=os-window --cwd=current ~/.config/kitty/tab-search.sh
map ctrl+f launch --type=overlay --os-window-class=floating-script ~/.config/kitty/tab-search.sh
map ctrl+shift+t combine : new_tab : sleep 0.01 : set_tab_title
# map ctrl+shift+t combine : new_tab : set_tab_title
# use this to refresh the config
# ctrl + shift + f5
