exec-once = qs
exec-once = ~/.config/waybar/launch.sh
exec-once = fcitx5 -d --replace
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = ~/.config/hypr/scripts/wallpaper-app.sh --restore
exec-once = ~/.config/hypr/scripts/gtk.sh
exec-once = swaync
exec-once = hypridle
exec-once = wl-paste --watch cliphist store
exec-once = ~/.config/hypr/scripts/cleanup.sh
