# SwayNC blur
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window

windowrule {
    name = pavucontrol
    match:class = (.*org.pulseaudio.pavucontrol.*)
    float = true
    center = true
    pin = true
    size = 700 600
}

windowrule {
    name = waypaper
    match:class = (.*waypaper.*)
    float = true
    center = true
    pin = true
    size = 900 700
}

windowrule {
    name = newelle
    match:class = (io.github.qwersyk.Newelle)
    float = true
    center = true
    pin = true
    size = 1000 700
}

windowrule {
    name = calendar
    match:class = (calendar)
    float = true
    move = 21 76
    pin = true
    size = 400 400
}

windowrule {
    name = sidebar
    match:class = (sidebar)
    float = true
    move = monitor_w-window_w-21 76
    pin = true
    size = 400 660
}

windowrule {
    name = blueman-manager
    match:class = (blueman-manager)
    float = true
    center = true
    size = 800 600
}

windowrule {
    name = nwg-look
    match:class = (nwg-look)
    float = true
    center = true
    size = 700 600
}

windowrule {
    name = nwg-displays
    match:class = (nwg-displays)
    float = true
    center = true
    size = 900 600
}

windowrule {
    name = missioncenter
    match:class = (io.missioncenter.MissionCenter)
    float = true
    center = true
    pin = true
    size = 900 600
}

windowrule {
    name = gnome-calculator
    match:class = (org.gnome.Calculator)
    float = true
    center = true
    size = 700 600
}

windowrule {
    name = hyprland-share-picker
    match:class = (hyprland-share-picker)
    float = true
    pin = true
    center = true
    size = 600 400
}

windowrule {
    name = nm-connection-editor
    match:class = (nm-connection-editor)
    float = true
    center = true
    size = 800 700
}

windowrule {
    name = Picture-in-Picture
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    float = true
    pin = true
    center = true
}

windowrule {
    name = dotfiles-floating
    match:class = (dotfiles-floating)
    float = true
    center = true
    size = 1000 700
}

windowrule {
    name = dotfiles-sidepad
    match:class = (dotfiles-sidepad)
    float = true
    pin = true
    center = true
    size = 1000 700
}
