# SwayNC blur
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window

windowrule {
    name = pavucontrol
    match:class = (.*org.pulseaudio.pavucontrol.*)
    float = true
    center = true
    pin = true
    size = 700 600
}

windowrule {
    name = waypaper
    match:class = (.*waypaper.*)
    float = true
    center = true
    pin = true
    size = 900 700
}

windowrule {
    name = newelle
    match:class = (io.github.qwersyk.Newelle)
    float = true
    center = true
    pin = true
    size = 1000 700
}

windowrule {
    name = ml4w-calendar
    match:class = (com.ml4w.calendar)
    float = true
    move = 21 76
    pin = true
    size = 400 400
}

windowrule {
    name = ml4w-sidebar
    match:class = (com.ml4w.sidebar)
    float = true
    move = monitor_w-window_w-21 76
    pin = true
    size = 400 660
}

windowrule {
    name = ml4w-welcome
    match:class = (com.ml4w.welcome)
    float = true
    center = true
    pin = true
    size = 700 600
}

windowrule {
    name = ml4w-welcome-app
    match:title = (ML4W Welcome)
    float = true
    center = true
    pin = true
    size = 700 600
}

windowrule {
    name = ml4w-settings
    match:class = (com.ml4w.settings)
    float = true
    move = monitor_w*0.5-window_w*0.5 86
    pin = true
    size = 900 600
}

windowrule {
    name = ml4w-settings-app
    match:title = (ML4W Dotfiles Settings)
    float = true
    move = monitor_w*0.5-window_w*0.5 86
    pin = true
    size = 900 600
}

windowrule {
    name = blueman-manager
    match:class = (blueman-manager)
    float = true
    center = true
    size = 800 600
}

windowrule {
    name = nwg-look
    match:class = (nwg-look)
    float = true
    center = true
    size = 700 600
}

windowrule {
    name = nwg-displays
    match:class = (nwg-displays)
    float = true
    center = true
    size = 900 600
}

windowrule {
    name = missioncenter
    match:class = (io.missioncenter.MissionCenter)
    float = true
    center = true
    pin = true
    size = 900 600
}

windowrule {
    name = gnome-calculator
    match:class = (org.gnome.Calculator)
    float = true
    center = true
    size = 700 600
}

windowrule {
    name = hyprland-share-picker
    match:class = (hyprland-share-picker)
    float = true
    pin = true
    center = true
    size = 600 400
}

windowrule {
    name = nm-connection-editor
    match:class = (nm-connection-editor)
    float = true
    center = true
    size = 800 700
}

windowrule {
    name = Picture-in-Picture
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    float = true
    pin = true
    center = true
}

windowrule {
    name = dotfiles-floating
    match:class = (dotfiles-floating)
    float = true
    center = true
    size = 1000 700
}

windowrule {
    name = dotfiles-sidepad
    match:class = (dotfiles-sidepad)
    float = true
    pin = true
    center = true
    size = 1000 700
}
