# -----------------------------------------------------
# Environment Variables
# name: "Default"
# -----------------------------------------------------
env = QT_IM_MODULE, fcitx
env = XMODIFIERS, @im=fcitx
# Note: GTK_IM_MODULE can sometimes break Wayland apps. 
# If they don't work, try changing 'fcitx' to 'wayland' below.
env = GTK_IM_MODULE, fcitx 

# Default Settings in ml4w.conf
